### PR TITLE
Feature/drf spectacular

### PR DESCRIPTION
**Pull request by annashamray**
Issue - https://github.com/maykinmedia/objects-api/issues/195 (the 3rd step)

### CODE REVIEW

**Review by joeribekker — CHANGES_REQUESTED** [review]
I noticed 2 things:
- The delete operations are called destroy here (same as it was in objects api)
- The objectversion resource seems to have 6 attributes marked as required which were not required in the pre-spectacular specification. I'll let you figure out if they ARE required or not. If they have defaults btw, these defaults should be documented in their description!

**Comment by annashamray** [comment]
@joeribekker 
1. Fixed
2. I think fields are not required since they are read-only. It turns out that there is a special setting parameter for it in `drf-spectacular` :)

**Review by joeribekker — APPROVED** [review]
Nice find, that setting. Do we need it in Objects API?

**Comment by annashamray** [comment]
@joeribekker  
Yes. I'll create an issue for it

**Comment by annashamray** [comment]
the issue - https://github.com/maykinmedia/objects-api/issues/210

**Pull request merged**
