### PR TITLE
:lipstick: fix help-text icon style in the admin

### PR DESCRIPTION
**Pull request by annashamray**
fixes https://github.com/open-zaak/open-notificaties/issues/150 (Objecttypes part)

### CODE REVIEW

**Review by Coperh — COMMENTED** [review]
Looks good. 

Not sure how much this actually matters but large help texts moves the next line instead of displaying over it. I could not figure out how to fix it myself


[Screencast from 02-07-24 14:14:23.webm](https://github.com/maykinmedia/objecttypes-api/assets/3464144/63a1922f-46b8-4b1b-92b2-0e76025f16bd)

Also the help text expands to fill the height.

**Comment by annashamray** [comment]
@Coperh Thanks for catching it. Next line is moving because the `position` was changed to `relative`, it should work now (I hope)

As for alignment of text and icon: `Allow geometry` is a checkbox field, and its label has different alignment then other fields (maybe we should fix it in the future). Help-text icon seems to align ok with other form fields, so I'll keep the alignment as it is for now

**Comment by annashamray** [comment]
I'll make the similar change in other PRs within https://github.com/open-zaak/open-notificaties/issues/150

**Review by Coperh — APPROVED** [review]
Works fine now

**Pull request merged**
