### PR TITLE
:bug:[maykinmedia/open-api-framework#39] make user emails unique

### PR DESCRIPTION
**Pull request by Coperh**
fixes: maykinmedia/open-api-framework#39

### CODE REVIEW

**Review by annashamray — COMMENTED** [review]
Should we add some code to check if existing emails are unique? 
@stevenbal @Coperh what do you think?

**Comment by stevenbal** [comment]
@annashamray hmm yeah, though I'm not sure what that check would do if it finds that there are duplicate emails :thinking:

**Comment by annashamray** [comment]
@stevenbal Maybe just some warning in the CHANGELOG for devops? So if migrations fail they will know why

**Comment by stevenbal** [comment]
I think that's a good idea :+1:

**Comment by Coperh** [comment]
@annashamray @stevenbal Added a warning to the changelog. Just want a review of this before I copy pasta it to my other PRs.

**Review by annashamray — APPROVED** [review]
:+1:

**Pull request merged**
