### PR TITLE
Release 2.2.0

### PR DESCRIPTION
**Pull request by SonnyBA**
Fixes https://github.com/maykinmedia/objects-api/issues/419

### CODE REVIEW

**Comment by SonnyBA** [comment]
After merging this PR, I assume it's merge commit should be tagged (and pushed). Are there any other steps to be taken after that?

**Review by annashamray — CHANGES_REQUESTED** [review]
Looks good, just some remarks:

1. In Changelog not all changes are buqfixes or QOL. Some looks like new features of infrastructure changes. Could you add sections for them and move related changed there
2. There was a release of 2.1.3 version. Could you add changed for it to the changelog? You can find them in `stablle/2.1.3` branch
3. Please update version in package-lok.json file

**Comment by annashamray** [comment]
@SonnyBA you are correct. after you merge the PR to `master` the commit in master branch is tagged. Please make the tag annotated and include in the description all the changes
You can use the existing tags as examples - https://github.com/maykinmedia/objecttypes-api/tags

**Review by annashamray — APPROVED** [review]
Please correct the format of the underline adornment, otherwise looks good!

**Pull request merged**
